{{- if eq (include "event-exporter.podWatchEnabled" .) "true" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "event-exporter.fullname" . }}
  labels:
    {{- include "event-exporter.labels" . | nindent 4 }}
{{- end }}
